HIAC/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

from . import views

app_name = 'HIAC'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('intro/', views.intro, name='intro'),
    path('account_setting/', views.account_setting, name='account_setting'),
    path('search_data/', views.search_data, name='search_data'),
    path('ok_button/', views.ok_button, name='ok_button'),
    path('download_button/', views.download_button, name='download_button'),
    path('donwload/', views.download, name='download'),
    path('upload_data/', views.upload_data, name='upload_data'),
    path('show_data/', views.show_data, name='show_data'),
    path('database_download/', views.database_download, name='database_download'),
    path('db_download/', views.db_download, name='db_download'),
    path('db_reset/', views.db_reset, name='db_reset'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HICCAccountingProgram/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('HIAC.urls')),
    path('admin/', admin.site.urls),
]

HIAC/models.py
from django.db import models


class AccountData(models.Model):
    user = models.CharField(max_length=50)
    transaction_date = models.DateTimeField()
    transaction_balance = models.IntegerField()
    transaction_detail = models.CharField(max_length=70)
    transaction_memo = models.CharField(max_length=70, blank=True, null=True)

HIAC/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, FileResponse
from django.core.files.storage import FileSystemStorage

from django.contrib import auth
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from collections import deque
from datetime import datetime
from .models import AccountData

import msoffcrypto
import pathlib
import pandas as pd
import numpy as np
import json
import os


# Create your views here.
leftTable = pd.DataFrame({'거래일시': [], '거래금액': [], '내용': [], '메모': []})
rightTable = pd.DataFrame({'거래일시': [], '거래금액': [], '내용': [], '메모': []})
totalStatistics = [0, 0, 0, 0]

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# 왼쪽 에서 부터 데이터 가 쌓이며 10개를 넘어갈 시 가장 오래된 데이터(맨 오른쪽)는 삭제 된다.
dataset_queue = deque()
dataset_queue.appendleft(rightTable)
queue_index = 0

intersection_index = list()
current_username = ''


def signup(request):
    if request.method == "POST":
        if request.POST.get('password1') == request.POST.get('password2'):
            user = User.objects.create_user(
                username=request.POST.get('username'),
                password=request.POST.get('password1'),
                email=request.POST.get('email'),
            )
            auth.login(request, user)
            return redirect('HIAC:login')
        return render(request, 'HIAC/signup.html')
    else:
        form = UserCreationForm
        return render(request, 'HIAC/signup.html', {'form': form})


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('HIAC:intro')
        else:
            context = {
                'error': 'username or password is incorrect.'
            }
            return render(request, 'HIAC/login.html', context)
    else:
        return render(request, 'HIAC/login.html')


def logout(request):
    auth.logout(request)
    return redirect('HIAC:login')


def intro(request):
    context = {}
    user = request.user
    context['user'] = user
    if request.method == 'POST' and 'excel' in request.FILES:
        uploaded_file = request.FILES['excel']
        fs = FileSystemStorage()
        name = fs.save(uploaded_file.name, uploaded_file)
        context = {
            'url': fs.url(name),
            'password_error': False
        }

    if request.method == "POST" and 'password_excel' in request.POST:
        pw = request.POST.get('password_excel')
        try:
            unlock_main(pw)
            read_exel()
            context['leftTable'] = True
            context.update({'password_error': False})

        except msoffcrypto.exceptions.InvalidKeyError:
            context.update({'password_error': True})

    return render(request, 'HIAC/intro.html', context)


def account_setting(request):
    global dataset_queue, queue_index, leftTable, rightTable, totalStatistics

    leftTable = leftTable.fillna("n/a")
    rightTable = rightTable.fillna("n/a")

    left_data = leftTable
    right_data = rightTable
    total_statistics_ = totalStatistics

    left_datalist = left_data.values.tolist()
    right_datalist = right_data.values.tolist()

    context = {
        'left_datalist': left_datalist,
        'right_datalist': right_datalist,
        'total_statistics': total_statistics_
    }

    # 옮기기 버튼을 눌렀을 때
    if request.method == "POST" and 'right_move' in request.POST:
        left_checklist = request.POST.getlist('left_checkbox[]')

        # checklist 받아온 것을 정수로 변환 하여 1씩 뺀 list => 선택된 데이터 의 행을 가져 와서 rightTable 에 넘긴다.
        if left_checklist:
            move_right(extract_rows(left_data, list(map(lambda x: x - 1, list(map(int, left_checklist))))))
            delete_overlap()
            push_deque(rightTable)

        right_data = rightTable
        right_datalist = right_data.values.tolist()
        context['right_datalist'] = right_datalist

        # statistics 계산
        if right_datalist:
            total = total_statistics(right_datalist)
            totalStatistics = total
            context.update({'total_statistics': total})
        else:
            context.update({'total_statistics': [0, 0, 0, 0]})

    # 삭제 하기 버튼을 눌렀을 때
    if request.method == "POST" and 'delete_data' in request.POST:
        right_checklist = request.POST.getlist('right_checkbox[]')

        if right_checklist:
            delete_row(list(map(lambda x: x - 1, list(map(int, right_checklist)))))
            push_deque(rightTable)

        new_right_data = rightTable
        new_right_datalist = new_right_data.values.tolist()
        context.update({'right_datalist': new_right_datalist})

        if new_right_datalist:
            new_total = total_statistics(new_right_datalist)
            totalStatistics = new_total
            context.update({'total_statistics': new_total})
        else:
            context.update({'total_statistics': [0, 0, 0, 0]})

    # 뒤로 가기 버튼을 눌렀을 때
    if request.method == "POST" and 'undo_data' in request.POST:
        if undo_data():
            right_datalist = dataset_queue[queue_index].values.tolist()
            context.update({'right_datalist': right_datalist})

            if right_datalist:
                total = total_statistics(right_datalist)
                totalStatistics = total
                context.update({'total_statistics': total})
            else:
                context.update({'total_statistics': [0, 0, 0, 0]})

        rightTable = dataset_queue[queue_index]

    # 앞으로 가기 버튼을 눌렀을 때
    if request.method == "POST" and 'redo_data' in request.POST:
        if redo_data():
            right_datalist = dataset_queue[queue_index].values.tolist()
            context.update({'right_datalist': right_datalist})

            if right_datalist:
                total = total_statistics(right_datalist)
                totalStatistics = total
                context.update({'total_statistics': total})
            else:
                context.update({'total_statistics': [0, 0, 0, 0]})

        rightTable = dataset_queue[queue_index]

    return render(request, 'HIAC/account_setting.html', context)


def search_data(request):
    json_object = json.loads(request.body)

    start = json_object.get('date_start')
    end = json_object.get('date_end')
    detail = json_object.get('detail')
    balance = json_object.get('balance')
    memo = json_object.get('memo')

    start_ = first_column_in_row(start)
    end_ = first_column_in_row(end)

    intersection(detail, balance, start_, end_, memo, False)
    search_dataframe = extract_rows(leftTable, intersection_index)

    solve_nan_search_dataframe = search_dataframe.fillna('n/a')
    # nan 처리를 해줘야 JSON parse 를 사용할 수 있다.

    search_dataframe_to_list = solve_nan_search_dataframe.values.tolist()

    search_list = []

    for i in range(0, len(search_dataframe_to_list)):
        search_dict = {
            'search_index': intersection_index[i],
            'transaction_time': search_dataframe_to_list[i][0],
            'transaction_balance': search_dataframe_to_list[i][1],
            'transaction_detail': search_dataframe_to_list[i][2],
            'transaction_memo': search_dataframe_to_list[i][3]
        }

        # 비어 있는 값이면 공백 으로 처리
        if search_dataframe_to_list[i][3] == 'n/a':
            search_dict.update({'transaction_memo': " "})

        search_list.append(search_dict)

    return JsonResponse({'dlist': search_list}, json_dumps_params={'ensure_ascii': False},
                        content_type="application/json")


def ok_button(request):
    global leftTable, totalStatistics
    json_response = json.loads(request.body)
    modal_checklist_not_num = json_response.get('check_list')

    modal_checklist = list(map(int, modal_checklist_not_num))

    context = {}

    if modal_checklist:
        table_ = extract_rows(leftTable, list(map(int, modal_checklist)))
        move_right(table_)
        delete_overlap()
        push_deque(rightTable)

    right_data = rightTable
    right_datalist = right_data.values.tolist()
    context['right_datalist'] = right_datalist

    # statistics 계산
    if right_datalist:
        total = total_statistics(right_datalist)
        totalStatistics = total
        context['total_statistics'] = total
    else:
        context['total_statistics'] = [0, 0, 0, 0]

    return render(request, 'HIAC/account_setting.html', context)


def download_button(request):
    global totalStatistics, rightTable

    statistics_dict = {
        '총 인원': totalStatistics[0],
        '총 입금': totalStatistics[1],
        '총 지출': totalStatistics[2],
        '입금-지출 차액': totalStatistics[3]
    }

    statistics_dataframe = pd.DataFrame(statistics_dict, index=['통계'])

    xlsx_dir = pathlib.Path(r'./HIAC/xlsx/xlsx3/output.xlsx')

    with pd.ExcelWriter(xlsx_dir) as writer:
        rightTable.to_excel(writer, sheet_name="추출 결과", index=False)
        statistics_dataframe.to_excel(writer, sheet_name="통계", index=False)

    return JsonResponse({"success_": "success"})


# download modal window 안의 저장 버튼을 눌렀을 때 파일 저장
def download(request):
    file_name = request.POST.get('file_name')

    src = pathlib.Path(r'./HIAC/xlsx/xlsx3/output.xlsx')
    xlsx_dir = pathlib.Path(r'./HIAC/xlsx/xlsx3')

    if file_name != "":
        file_name_change = file_name + '.xlsx'
        dst = os.path.join(xlsx_dir, file_name_change)
        os.rename(src, dst)

        fs = FileSystemStorage(xlsx_dir)
        response = FileResponse(fs.open(file_name_change, 'rb'), content_type='application/vnd.ms-excel')

        return response

    else:
        file_name_change = 'HIAC.xlsx'
        dst = os.path.join(xlsx_dir, file_name_change)
        os.rename(src, dst)

HIAC/templates/HIAC/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

HIAC/templates/HIAC/intro.html
{% extends 'base.html' %}

{% block body %}

    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal">회계 자동화 프로그램 <a href="https://github.com/HICC-Bootcamp/2022-import4ky-HICCAccountingProgram" style="font-size: 2em"> HIAC</a> 입니다.</h1>
        </div>
    </header>

    <article>
        <div class="container d-flex h-100">
          <div class="row justify-content-center align-self-center">
              <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" name="excel" id="input-file-now" class="file-upload"/>
                <button type="submit">Upload excel file</button>
                {% if url %}
                    <span>Excel file entered successfully!</span>
                {% endif %}
              </form>
              <div class="card" style="width:700px;">
                <div class="card-body">
                   <div class="row">
                        <div class="col-lg-12 col-sm-12 text-lg-start text-center" style="margin-bottom:30px">
                            <h4 class="card-title">
                                {{ user }}님 환영합니다. <a href="{% url 'HIAC:logout' %}">logout</a>
                            </h4>
                            <h5>excel 파일을 드래그 앤 드랍 하세요.</h5>
                        </div>
                        <div class="col-lg-12 col-sm-12 text-lg-start text-center" style="margin-bottom:30px">
                            <form method="post">
                                {% csrf_token %}
                                <label for="pass">Password (6 digits minimum)</label>
                                <br>
                                <input type="password" id="pass" name="password_excel" minlength="6" required disabled />
                                <br><br>
                                <span>
                                    <button type="submit" class="btn btn-secondary" id="pwBtn" disabled>확인</button>
                                    <button type="button" class="btn btn-secondary" id="pageMove"
                                            onclick="location.href={% url 'HIAC:account_setting' %}" disabled>이동</button>
                                </span>
                            </form>
                        </div>
                   </div>
                </div>
              </div>
          </div>
         </div>
    </article>

<!-- JS 연결 !-->
<script>
    let url = "{{ url| safe }}";
    let left_table = "{{ leftTable| safe }}";
    let password_error = "{{ password_error| safe }}";
</script>

<!-- 폰트 적용 !-->
<style>
    body {
        font-family: 'GangwonEdu_OTFBoldA', sans-serif;
    }
</style>

{% endblock %}

HIAC/templates/HIAC/login.html
{% extends 'base.html' %}

{% block body %}

    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal">회계 자동화 프로그램 <a href="https://github.com/HICC-Bootcamp/2022-import4ky-HICCAccountingProgram" style="font-size: 2em"> HIAC</a> 입니다.</h1>
        </div>
    </header>

    <article>
        <div id="login">
            <div class="container">
                <div id="login-row" class="row justify-content-center align-items-center">
                    <div id="login-column" class="col-md-6">
                        <div id="login-box" class="col-md-12" style="height: 460px;">
                            <form id="login-form" class="form" action="{% url 'HIAC:login' %}" method="post">
                                {% csrf_token %}
                                {% include "HIAC/form_errors.html" %}
                                <h3 class="text-center text-info">Login</h3>
                                <div class="form-group">
                                    <label for="username" class="text-info">Username:</label><br>
                                    <input type="text" name="username" id="username" class="form-control"
                                            value="{{ form.username.value|default_if_none:'' }}">
                                </div>
                                <div class="form-group">
                                    <label for="password" class="text-info">Password:</label><br>
                                    <input type="password" name="password" id="password" class="form-control"
                                            value="{{ form.username.value|default_if_none:'' }}">
                                </div>
                                <div class="form-group">
                                    <br>
                                    <input type="submit" name="submit" class="btn btn-info btn-md" value="submit">
                                </div>
                                <div id="register-link" class="text-right">
                                    <br>
                                    <a href="{% url 'HIAC:signup' %}" class="text-info">Register here</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </article>


<!-- 폰트 적용 !-->
<style>
    body {
        font-family: 'GangwonEdu_OTFBoldA', sans-serif;
    }
</style>

{% endblock %}

HIAC/templates/HIAC/show_data.html
{% extends 'base.html' %}

{% block body %}
{% if user.is_authenticated %}
{% load static %}
    <header>
        <div class="show_data_header_window">
            <a href="{% url 'HIAC:intro' %}"> <img src= "{% static 'img/logo.png'%}" alt="HIAC" id="show_logo"></a>
            <h2 id="show_data_header">{{ user.username }}님의 데이터 보기</h2>
            <a href="{% url 'HIAC:logout' %}" id="show_data_logout_btn_a_tag">logout</a>
        </div>
    </header>

    <article>
        <div class="show_toolbar">
            <a href="{% url 'HIAC:account_setting' %}" id="go_account_setting">
                <span class="material-symbols-outlined" title="뒤로 가기" id="go_account_feed">undo</span>
            </a>
            <button type="button" onclick="database_download_button_clicked()" name="db_download_data" id="db_download_btn_feed">
                    <span class="material-symbols-outlined" title="다운로드 하기" id="db_download_excel">file_download</span>
            </button>
            <button type="submit" name="db_reset" form="db_reset_form" id="db_reset_feed">
                    <span class="material-symbols-outlined" title="데이터베이스 초기화" id="db_reset">delete_forever</span>
            </button>
        </div>
        <div class="search_mainWindow">
            <div class="search_leftTable">
                <form id="show_left_table_form" method="post">
                {% csrf_token %}
                    <table class="table">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">거래 일자</th>
                                <th scope="col">거래 금액</th>
                                <th scope="col">거래 내용</th>
                                <th scope="col">메모</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for data in datalist %}
                            <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                <td>{{ data.transaction_date| safe }}</td>
                                <td>{{ data.transaction_balance| safe }}</td>
                                <td>{{ data.transaction_detail| safe }}</td>
                                <td>{{ data.transaction_memo| safe }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </form>
            </div>
            <div class="search_rightTable">
                <div class="search_data_requirement">
                    <div class="search_data_requirement_title_window">
                        <div class="search_data_requirement_title_side"></div>
                        <h3 id="search_data_requirement_title">검색 조건 설정</h3>
                        <div class="search_data_requirement_title_side"></div>
                    </div>
                    <form method="post" id="search_data_form" action="{% url 'HIAC:show_data' %}">
                        {% csrf_token %}
                        <div class="search_data_find_date">
                            <input type="checkbox" id="search_date_feed" name="search_date_feed" value=0 onchange="showDateInputManage()"/>
                            <label for="date_feed" id="search_date_label">기간</label>
                            <label for="start_day" id="search_start_day_label">시작일</label>
                            <input type="date" id="search_start_day" name="search_start_day" disabled>
                            <label for="end_day" id="search_end_day_label">종료일</label>
                            <input type="date" id="search_end_day" name="search_end_day" disabled>
                        </div>
                        <div class="search_data_find_detail">
                            <input type="checkbox" id="search_detail_feed" name="search_detail_feed" value=0 onchange="showDetailInputManage()"/>
                            <label for="detail_feed" id="search_detail_label">내용</label>
                            <input type="text" id="search_detail_input" name="search_detail_input" placeholder="내용을 입력해 주세요" disabled>
                        </div>
                        <div class="search_data_find_balance">
                            <input type="checkbox" id="search_balance_feed" name="search_balance_feed" value=0 onchange="showBalanceInputManage()"/>
                            <label for="balance_feed" id="search_balance_label">금액</label>
                            <input type="text" id="search_balance_input" name="search_balance_input" placeholder="금액을 입력해 주세요" disabled>
                        </div>
                        <div class="search_data_find_memo">
                            <input type="checkbox" id="search_memo_feed" name="search_memo_feed" value=0 onchange="showMemoInputManage()"/>
                            <label for="memo_feed" id="search_memo_label">메모</label>
                            <input type="text" id="search_memo_input" name="search_memo_input" placeholder="메모를 입력해 주세요" disabled>
                        </div>
                    </form>
                    <div class="search_button_group">
                        <div class="search_button_group_side"></div>
                        <button type="submit" class="btn btn-secondary" form="search_data_form" id="search_form_btn" name="search_form_btn">검색</button>
                        <div class="search_button_group_side"></div>
                    </div>
                </div>
                <div class="show_total">
                     <table class="table">
                          <thead class="thead-light">
                          <tr>
                              <th scope="col">총 인원</th>
                              <th scope="col">총 입금</th>
                              <th scope="col">총 지출</th>
                              <th scope="col">입금-지출 차액</th>
                          </tr>
                          </thead>
                          <tbody>
                            <tr>
                                <td>{{ total_statistics.0 }}</td>
                                <td>{{ total_statistics.1 }}</td>
                                <td>{{ total_statistics.2 }}</td>
                                <td>{{ total_statistics.3 }}</td>
                            </tr>
                          </tbody>
                     </table>
                </div>
            </div>
        </div>
    </article>
    <footer>
        <form method="post" action="{% url 'HIAC:db_reset' %}" id="db_reset_form">
            {% csrf_token %}
        </form>
    </footer>

     <!-- download modal window !-->
    <div id="db_download_modal_feed" class="db_download_modal_overlay">
        <div class="db_download_modal_window">
            <div class="db_download_modal_title">
                <div class="db_download_modal_title_side"></div>
                <div> 다운로드 하기 </div>
                <div class="db_download_modal_title_side">
                    <span id="db_close_download_modal" class="material-symbols-outlined">close</span>
                </div>
            </div>
            <div class="db_download_window">
                <div class="db_file_name_input_window">
                    <form method="post" action="{% url 'HIAC:db_download' %}" id="db_download_form">
                      {% csrf_token %}
                      <label for="db_file_name_input" id="db_file_name_input_label">문서명 입력</label>
                      <input type="text" name="db_file_name" id="db_file_name_input" placeholder="문서명을 입력해주세요">
                    </form>
                </div>
                <div class="db_download_button_window">
                    <div class="db_download_button_window_side"></div>
                    <button type="submit" form="db_download_form" class="btn btn-secondary" id="db_download_button_feed">저장</button>
                    <div class="db_download_button_window_side"></div>
                </div>
            </div>
        </div>
    </div>


    <!-- Google material icon, font 적용 !-->
    <style>
        .material-symbols-outlined {
             font-variation-settings:
            'FILL' 0,
            'wght' 400,
            'GRAD' 0,
            'opsz' 48
        }

        body {
            font-family: 'GangwonEdu_OTFBoldA', sans-serif;
            width: 1204px;
            height: 1100px;
            margin: 0;
            padding: 0;
        }
    </style>

    <script>
        let url_database_download_button = {% url 'HIAC:database_download' %};

         function database_download_button_clicked() {
             $.ajax({
                 url: url_database_download_button,
                 type: "POST",
                 headers: {
                     'X-CSRFTOKEN': '{{ csrf_token }}'
                 },
                 data: null,
                 complete: function(response) {
                     let success = JSON.parse(response.responseText);
                     console.log(success.success_);
                 }
             });
        }
    </script>

{% else %}
    <div class="login_error">
        비정상적인 접근입니다. 로그인 후 이용하시기 바랍니다.
    </div>
{% endif %}

{% endblock %}

HIAC/templates/HIAC/signup.html
{% extends 'base.html' %}

{% block body %}
    <div class="container">
        <div class="input-form-background row">
            <div class="input-form col-md-12 mx-auto">
                <h4 class="mb-3">SignUp</h4>
                <form class="validation-form" method="post" action="{% url 'HIAC:signup' %}">
                    {% csrf_token %}
                    {% include "HIAC/form_errors.html" %}
                    <div class="mb-3">
                        <label for="username">username</label>
                        <input type="text" class="form-control" id="username" name="username" placeholder=""
                               value="{{ form.username.value|default_if_none:'' }}" required>
                        <div class="invalid-feedback">
                            Name input is required.
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="password1">Password</label>
                        <input type="password" class="form-control" id="password1" name="password1"
                               value="{{ form.password1.value|default_if_none:'' }}" required>
                        <div class="invalid-feedback">
                            Password input is required.
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="password2">Confirm Password</label>
                        <input type="password" class="form-control" id="password2" name="password2"
                               value="{{ form.password2.value|default_if_none:'' }}" required>
                        <div class="invalid-feedback">
                            password input is required.
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="email">Email</label>
                        <input type="email" class="form-control" id="email" name="email" placeholder="hicc@hongik.ac.kr"
                               value="{{ form.email.value|default_if_none:'' }}" required>
                        <div class="invalid-feedback">
                            Email input is required.
                        </div>
                    </div>
                    <div class="mb-4"></div>
                    <button type="submit" class="btn btn-primary btn-lg btn-black">
                        Register
                    </button>
                </form>
            </div>
        </div>
    </div>

    <script>
        window.addEventListener('load', () => {
            const forms = document.getElementsByClassName('validation-form');

            Array.prototype.filter.call(forms, (form) => {
                form.addEventListener('submit', function (e) {
                    if (form.checkValidity() === false) {
                        e.preventDefault();
                        e.stopPropagation();
                    }

                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    </script>

{% endblock %}